#!/bin/bash

RED="\033[0;32m"
GREEN="\033[0;32m"
NC="\e[0m"
clear

echo ""
echo -e "${RED}==============================================================$NC"
echo -e "${RED} ------------------------------------------------------------$NC" 
echo "   >>> Service & Port"
echo "   - Nginx                   : 81"
echo "   - XRAY Vmess TLS          : 443"
echo "   - XRAY Vmess Non TLS      : 80"
echo "   - XRAY Vmess GRPC         : 443"
echo "   - XRAY Vless TLS          : 443"
echo "   - XRAY Vless Non TLS      : 80"
echo "   - XRAY Vless GRPC         : 443"
echo "   - Trojan TCP TLS          : 443"
echo "   - Trojan GRPC             : 443"
echo "   - Trojan WS               : 443"
echo "   - Shadowsocks WS TLS      : 443"
echo "   - Shadowsocks GRPC        : 443"
echo ""  | tee -a log-install.txt
echo "   >>> Server Information & Other Features"
echo "   - Timezone                : Asia/Jakarta (GMT +7)"
echo "   - Fail2Ban                : [ON]"
echo "   - Dflate                  : [ON]"
echo "   - IPtables                : [ON]"
echo "   - Auto-Reboot             : [ON]"
echo "   - IPv6                    : [OFF]"
echo "   - Autoreboot On           : 05:00 WIB GMT +7"
echo "   - Auto Delete Expired Account"
echo "   - Fully automatic script"
echo "   - VPS settings"
echo "   - Admin Control"
echo "   - Full Orders For Various Services"
echo -e "${RED} ------------------------------------------------------------$NC"
echo -e "${RED}==============================================================$NC"
